version: '3'
services:
  db:
    image: postgres:11
    ports:
      - "54320:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=recipes